<center> <h1>Universidad Nacional de San Agustín de Arequipa</h1> </center>
<center> <h1>Escuela Profesional de Ingeniería de Telecomunicaciones</h1> </center>

<center> <h1> </h1> </center>

<center><img src="https://user-images.githubusercontent.com/19308295/115939517-f1c6fe80-a463-11eb-989c-812ab4942586.png" width="280" height="400"></center>

<center> <h2>Tarea en Grupo: Computacion2 B-4</h2> </center>

<center> <h1>Curso : Computación 2</h1> </center>

![linea 1](https://user-images.githubusercontent.com/19308295/115926252-2b8a0c00-a448-11eb-9d9c-b43beaf0ff68.png)

<center> <h1>PANDAS</h1> </center>

![linea 1](https://user-images.githubusercontent.com/19308295/115926252-2b8a0c00-a448-11eb-9d9c-b43beaf0ff68.png)

# Descripción:

<div class="alert alert-info">

En este notebook se explicarán la librería **Pandas** escrita como extensión de **NumPy** para la manipulación y análisis de datos en el lenguaje de programación Python.
    
</div>

# Objetivos:

 1. Familiarizarce con creación de la estructura de tabla de datos **DataFrame.**
 2. Manejo inicial de un **DataFrame.**
 3. Importando archivos ***csv*** y manipulación inicial en **Pandas.**



[1. Pandas](#1.-Pandas)<br>
[2. Creación de DataFrame](#2.-Creación-de-DataFrame)<br>
[3. DataFrame a partir de archivo CSV](#3.-DataFrame-a-partir-de-archivo-CSV)<br>
[4. Estadistica DataFrame](#4.-Estadistica-DataFrame)<br>

[EJEMPLOS](#EJEMPLOS)<br>
[EJERCICIOS](#EJERCICIOS)<br>
[BIBLIOGRAFÍA](#BIBLIOGRAFÍA)<br>

![linea 1](https://user-images.githubusercontent.com/19308295/115926252-2b8a0c00-a448-11eb-9d9c-b43beaf0ff68.png)

![640px-Pandas_logo svg](https://user-images.githubusercontent.com/19308295/119273971-1b925300-bbd3-11eb-9705-fa3a404af0e1.png)

## <font color=#33A5FF>****1. Pandas****<tfont>

<div class="well">
<strong>PanDaS  (Panel Data Set)</strong>  es una librería de Python para la <strong>ciencia de datos y Machine Learning</strong>, por muchas razones, ofrece estructuras de datos poderosas, expresivas y flexibles que facilitan la manipulación y análisis de datos. Entre las estructuras más utilizadas se encuentra el <strong>DataFrame</strong>.

<strong>Pandas</strong> es una librería de código abierto de Python que proporciona herramientas de análisis y manipulación de datos de alto rendimiento utilizando sus potentes estructuras de datos.
    
    
</div>

<div class="well">
La librería <strong>Pandas</strong> se desarrollo debido a la necesidad de tener una herramienta flexible de alto rendimiento para el análisis de datos, construido sobre Numpy. En Python se utiliza  <strong>pandas</strong> en Machine Learning para la manipulación y preparación de datos.

Usando esta librería podemos lograr cinco pasos típicos en el procesamiento y análisis de datos, independientemente del origen de los datos:
</div>
     
    
   - Cargar
   - Preparar
   - Manipular
   - Modelar
   - Analizar

<div class="well">
    Caracteristicas principales de de la librería <strong>Pandas</strong>.
</div>   
   
   
   
   - Objeto DataFrame rápido y eficiente con indexación predeterminada y personalizada.
   - Alto rendimiento para cargar datos en objetos de datos en memoria desde diferentes formatos de archivo.
   - Alineación de datos y manejo integrado de datos faltantes.
   - Remodelación y giro de conjuntos de fechas.
   - Etiquetado, corte, indexación y subconjunto de grandes conjuntos de datos.
   - Las columnas de una estructura de datos se pueden eliminar o insertar.
   - Agrupa por datos para agregación y transformaciones.
   - Alto rendimiento de fusión y unión de datos.
   - Funcionalidad de la serie de tiempo.

## DataFrame

<div class="well">
Es una estructura de datos muy utilizada en <strong>pandas</strong>, es tabular bidimensional de tamaño variable y potencialmente heterogénea con ejes etiquetados (filas y columnas).

Un <strong>DataFrame</strong>  es una estructura de datos bidimensional, es decir, los datos se alinean de forma tabular en filas y columnas. Pandas DataFrame consta de tres componentes principales:
</div>



   - Los datos
   - Las filas
   - Las columnas

![Pantas_DataFrame](https://user-images.githubusercontent.com/19308295/119273989-44b2e380-bbd3-11eb-96d1-bd7e8a928fd6.png)

<div class="alert alert-info">

Si hablamos de la estructura de un **DataFrame** es muy similar a la de una matriz. Pero en una matriz solamente se admiten valores numéricos, a diferencia de la matriz, en un **DataFrame** se puede incluir también datos alfanuméricos en su contenido.


</div>

![linea 2](https://user-images.githubusercontent.com/19308295/115926262-2fb62980-a448-11eb-8189-c2f10e499944.png)

## <font color=#33A5FF>****EJERCICIOS****<tfont>

### Ejercicio 1 - Investigar Como? Abrir archivo `xlsx`

<div class="well">Abrilr el archivo <code>titanic.xlsx</code> (archivo en carpeta /data)
    
   1.- <strong>Usar nueva librería!!.</strong>

   2.- <strong>Explorar la data.</strong>
</div>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')
titanic = pd.read_excel('/content/drive/MyDrive/titanic.xlsx')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#Para ver cuantas filas por columnas hay
titanic.shape

(891, 11)

In [ ]:
titanic.dtypes

Id_Pasajero      int64
Survived         int64
Clase            int64
Nombre          object
Sexo            object
Edad           float64
Familiares       int64
Tiquete         object
Tarifa         float64
Cabina          object
Embarcado       object
dtype: object

In [ ]:
#Para ver cuantos datos por columnas hay
titanic.count()

Id_Pasajero    891
Survived       891
Clase          891
Nombre         891
Sexo           891
Edad           714
Familiares     891
Tiquete        891
Tarifa         891
Cabina         204
Embarcado      889
dtype: int64

In [ ]:
#Para ver los 5 primeras filas
titanic.head()

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
0,1,0,3,"Braund, Mr. Owen Harris",Masculino,22.0,0,A/5 21171,7.25,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",Femenino,26.0,0,STON/O2. 3101282,7.93,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",Masculino,35.0,0,373450,8.05,NaN,S

In [ ]:
#Para ver las ultimas 5 filas
titanic.tail()

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
886,887,0,2,"Montvila, Rev. Juozas",Masculino,27.0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",Femenino,19.0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",Femenino,NaN,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",Masculino,26.0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",Masculino,32.0,0,370376,7.75,NaN,Q

In [ ]:
#cNos da en un cuadro la cantidad de datos count, media mean, desviación estandar std,
#valor mínimo min, valor máximo,los percentiles inferior de 25% y el percentil superior de 75%.
titanic.describe()

       Id_Pasajero    Survived       Clase        Edad  Familiares      Tarifa
count   891.000000  891.000000  891.000000  714.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.381594   32.205017
std     257.353842    0.486592    0.836071   14.526497    0.806057   49.693389
min       1.000000    0.000000    1.000000    0.420000    0.000000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000    7.915000
50%     446.000000    0.000000    3.000000   28.000000    0.000000   14.450000
75%     668.500000    1.000000    3.000000   38.000000    0.000000   31.000000
max     891.000000    1.000000    3.000000   80.000000    6.000000  512.330000

In [ ]:
#Hallamos el promedio de cada columna
titanic_numericos = titanic.select_dtypes(include=['float','int'])
titanic_numericos.mean()

Id_Pasajero    446.000000
Survived         0.383838
Clase            2.308642
Edad            29.699118
Familiares       0.381594
Tarifa          32.205017
dtype: float64

In [ ]:
#Correlacion del Dataframe
titanic_numericos.corr()

             Id_Pasajero  Survived     Clase      Edad  Familiares    Tarifa
Id_Pasajero     1.000000 -0.005007 -0.035144  0.036847   -0.001652  0.012659
Survived       -0.005007  1.000000 -0.338481 -0.077221    0.081629  0.257303
Clase          -0.035144 -0.338481  1.000000 -0.369226    0.018443 -0.549490
Edad            0.036847 -0.077221 -0.369226  1.000000   -0.189119  0.096062
Familiares     -0.001652  0.081629  0.018443 -0.189119    1.000000  0.216228
Tarifa          0.012659  0.257303 -0.549490  0.096062    0.216228  1.000000

In [ ]:
#Para encontrar el dato minimo de cada columna
titanic_numericos.min()

Id_Pasajero    1.00
Survived       0.00
Clase          1.00
Edad           0.42
Familiares     0.00
Tarifa         0.00
dtype: float64

In [ ]:
#Para encontrar el dato maximo de cada columna
titanic_numericos.max()

Id_Pasajero    891.00
Survived         1.00
Clase            3.00
Edad            80.00
Familiares       6.00
Tarifa         512.33
dtype: float64

In [ ]:
#Para encontrar la desviacion estadar  por columna
titanic_numericos.std()

Id_Pasajero    257.353842
Survived         0.486592
Clase            0.836071
Edad            14.526497
Familiares       0.806057
Tarifa          49.693389
dtype: float64

In [ ]:
#Para ver la primera columna del DataFrame
titanic.iloc[:, 0]   #Recordar que el primero es filas y el segundo es columnas

0        1
1        2
2        3
3        4
4        5
      ...
886    887
887    888
888    889
889    890
890    891
Name: Id_Pasajero, Length: 891, dtype: int64

In [ ]:
#Para ver hasta la 2da columna del DataFrame
titanic.iloc[:, 0:2]    #OJO: al solo poner ':' quiere decir todos los valores

     Id_Pasajero  Survived
0              1         0
1              2         1
2              3         1
3              4         1
4              5         0
..           ...       ...
886          887         0
887          888         1
888          889         0
889          890         1
890          891         0

[891 rows x 2 columns]

In [ ]:
#Selecciona la primera fila '0' y la 2da columna '1'(Survived)
titanic.iloc[0][1]

0

In [ ]:
#Quiere decir que se nos mostrará todos los datos de la primera fila
titanic.loc[0]

Id_Pasajero                          1
Survived                             0
Clase                                3
Nombre         Braund, Mr. Owen Harris
Sexo                         Masculino
Edad                              22.0
Familiares                           0
Tiquete                      A/5 21171
Tarifa                            7.25
Cabina                             NaN
Embarcado                            S
Name: 0, dtype: object

In [ ]:
#Este es otromodo de escribir que el anterior
titanic.iloc[0, :] #La diferencia es que aveces ':' no se pone cuando queremos todos los datos

Id_Pasajero                          1
Survived                             0
Clase                                3
Nombre         Braund, Mr. Owen Harris
Sexo                         Masculino
Edad                              22.0
Familiares                           0
Tiquete                      A/5 21171
Tarifa                            7.25
Cabina                             NaN
Embarcado                            S
Name: 0, dtype: object

In [ ]:
#Para poder ver los nombres de las columnas
titanic.columns

Index(['Id_Pasajero', 'Survived', 'Clase', 'Nombre', 'Sexo', 'Edad',
       'Familiares', 'Tiquete', 'Tarifa', 'Cabina', 'Embarcado'],
      dtype='object')

In [ ]:
#Puse ':' para que me mostrara todas las filas pero mencione 3 columnas para que solo me muestre eso
titanic.loc[: ,['Id_Pasajero','Nombre','Survived']]

     Id_Pasajero                                             Nombre  Survived
0              1                            Braund, Mr. Owen Harris         0
1              2  Cumings, Mrs. John Bradley (Florence Briggs Th...         1
2              3                             Heikkinen, Miss. Laina         1
3              4       Futrelle, Mrs. Jacques Heath (Lily May Peel)         1
4              5                           Allen, Mr. William Henry         0
..           ...                                                ...       ...
886          887                              Montvila, Rev. Juozas         0
887          888                       Graham, Miss. Margaret Edith         1
888          889           Johnston, Miss. Catherine Helen "Carrie"         0
889          890                              Behr, Mr. Karl Howell         1
890          891                                Dooley, Mr. Patrick         0

[891 rows x 3 columns]

In [ ]:
#Hemos creado una nueva columna que saca el promedio de la tarifa y la clase
titanic['Promedio de la tarifa y la clase']=(titanic['Tarifa']+titanic['Clase'])/2
titanic.head()

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado,Promedio de la tarifa y la clase
0,1,0,3,"Braund, Mr. Owen Harris",Masculino,22.0,0,A/5 21171,7.25,NaN,S,5.125
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C,36.140
2,3,1,3,"Heikkinen, Miss. Laina",Femenino,26.0,0,STON/O2. 3101282,7.93,NaN,S,5.465
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S,27.050
4,5,0,3,"Allen, Mr. William Henry",Masculino,35.0,0,373450,8.05,NaN,S,5.525

In [ ]:
#Aquí se aprecia como se aumento una columna con el nombre de Promedio de la tarifa y la clase
titanic.columns

Index(['Id_Pasajero', 'Survived', 'Clase', 'Nombre', 'Sexo', 'Edad',
       'Familiares', 'Tiquete', 'Tarifa', 'Cabina', 'Embarcado',
       'Promedio de la tarifa y la clase'],
      dtype='object')

In [ ]:
#En este caso solo me imprime los datos de las personas que han sobrevivido, o sea el 1
titanic.loc[titanic['Survived']== 1]

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",Femenino,26.0,0,STON/O2. 3101282,7.93,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",Femenino,27.0,2,347742,11.13,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",Femenino,14.0,0,237736,30.07,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",Femenino,15.0,0,2667,7.23,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",Femenino,56.0,1,11767,83.16,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",Femenino,25.0,1,230433,26.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",Femenino,19.0,0,112053,30.00,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",Masculino,26.0,0,111369,30.00,C148,C

In [ ]:
#En este caso la cantidad de personas que han sobrevivido son 342 ya que solo se crea un DatFrame de 342 x 11
titanic.loc[titanic['Survived']== 1].shape
#Conclusion solo sobrevivieron 342 personas de 889

(342, 11)

In [ ]:
#En este caso solo quiero que se muestre los datos de las personas de 1ra clase
display(titanic.loc[titanic['Clase']== 1])

#Con len podemos saber la cantidad de filas
first_class = len(titanic.loc[titanic['Clase']== 1])
#Por ende la cantidad de personas de primera clase
print("\nLa cantidad de personas que son de primera clase es: ",first_class)

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",Masculino,54.0,0,17463,51.86,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",Femenino,58.0,0,113783,26.55,C103,S
23,24,1,1,"Sloper, Mr. William Thompson",Masculino,28.0,0,113788,35.50,A6,S
...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",Femenino,47.0,1,11751,52.55,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",Masculino,33.0,0,695,5.00,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",Femenino,56.0,1,11767,83.16,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",Femenino,19.0,0,112053,30.00,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",Masculino,26.0,0,111369,30.00,C148,C

La cantidad de personas que son de primera clase es:  216

In [ ]:
#En este caso hallamos la cantidad de personas de primera Clase que hayan sobrevivido
survived_firstClass = titanic.loc[(titanic['Survived']==1) & (titanic['Clase']==1)]
display(survived_firstClass)

cantidad_survived_firstClass = len(survived_firstClass)
print("\nLa cantidad de personas que son de primera clase es: ",cantidad_survived_firstClass)

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
11,12,1,1,"Bonnell, Miss. Elizabeth",Femenino,58.0,0,113783,26.55,C103,S
23,24,1,1,"Sloper, Mr. William Thompson",Masculino,28.0,0,113788,35.50,A6,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",Femenino,NaN,0,PC 17569,146.52,B78,C
...,...,...,...,...,...,...,...,...,...,...,...
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",Femenino,48.0,0,17466,25.93,D17,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",Femenino,47.0,1,11751,52.55,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",Femenino,56.0,1,11767,83.16,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",Femenino,19.0,0,112053,30.00,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",Masculino,26.0,0,111369,30.00,C148,C

La cantidad de personas que son de primera clase es:  136

In [ ]:
#Aquí podemos ver la cantidad y otros datos más
survived_firstClass.count()

Id_Pasajero    136
Survived       136
Clase          136
Nombre         136
Sexo           136
Edad           122
Familiares     136
Tiquete        136
Tarifa         136
Cabina         117
Embarcado      134
dtype: int64

In [ ]:
#Para eleiminar la columna, en este caso Familiares(6) y Tiquete(7)
titanic_modificado=titanic.copy()
columna_eliminar=[6,7]

titanic_modificado.drop(titanic_modificado.columns[columna_eliminar], axis=1, inplace=True)
titanic_modificado.head()

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Tarifa,Cabina,Embarcado
0,1,0,3,"Braund, Mr. Owen Harris",Masculino,22.0,7.25,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,71.28,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",Femenino,26.0,7.93,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",Masculino,35.0,8.05,NaN,S

### Ejercicio 2 - Investigar Como? Crear SubConjuntos

<div class="well">Crear <strong>Sub Conjuntos</strong> del DataFrame con las columnas: (visualizar solo 5 primeros)
   
   1.-<strong>Nombre</strong> con <strong>Edad</strong>
   
   2.-<strong>Sexo</strong> con <strong>Nombre</strong> y <strong>Clase</strong>
    
</div>

In [ ]:
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
titanic = pd.read_excel('/content/drive/MyDrive/titanic.xlsx')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
titanic.head()

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
0,1,0,3,"Braund, Mr. Owen Harris",Masculino,22.0,0,A/5 21171,7.25,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",Femenino,26.0,0,STON/O2. 3101282,7.93,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",Masculino,35.0,0,373450,8.05,NaN,S

In [ ]:
#Gráfico nombre con Edad
#Manera n°1
titanic_Nombre_Edad= titanic.copy()
lista_eliminar = [0,1,2,4,6,7,8,9,10]
titanic_Nombre_Edad.drop((titanic_Nombre_Edad).columns[lista_eliminar], axis=1, inplace=True)
titanic_Nombre_Edad.head(6)

                                              Nombre  Edad
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                           Allen, Mr. William Henry  35.0
5                                   Moran, Mr. James   NaN

In [ ]:
#Manera n°2
titanic_Nombre_Edad.loc[: ,['Nombre','Edad']]
titanic_Nombre_Edad.head()

                                              Nombre  Edad
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                           Allen, Mr. William Henry  35.0

In [ ]:
#Grafico sexo con Nombre y Clase
#Manera 1
titanic_Sexo_Nombre_Clase= titanic.copy()
lista_eliminar = [0,1,5,6,7,8,9,10]
titanic_Sexo_Nombre_Clase.drop((titanic_Sexo_Nombre_Clase).columns[lista_eliminar], axis=1, inplace=True)
titanic_Sexo_Nombre_Clase.head(6)

   Clase                                             Nombre       Sexo
0      3                            Braund, Mr. Owen Harris  Masculino
1      1  Cumings, Mrs. John Bradley (Florence Briggs Th...   Femenino
2      3                             Heikkinen, Miss. Laina   Femenino
3      1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   Femenino
4      3                           Allen, Mr. William Henry  Masculino
5      3                                   Moran, Mr. James  Masculino

In [ ]:
#Manera n°2
titanic_Sexo_Nombre_Clase.loc[: ,['Sexo','Nombre','Clase']]
titanic_Sexo_Nombre_Clase.head(6)

   Clase                                             Nombre       Sexo
0      3                            Braund, Mr. Owen Harris  Masculino
1      1  Cumings, Mrs. John Bradley (Florence Briggs Th...   Femenino
2      3                             Heikkinen, Miss. Laina   Femenino
3      1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   Femenino
4      3                           Allen, Mr. William Henry  Masculino
5      3                                   Moran, Mr. James  Masculino

### Ejercicio 3 - Investigar Como? Filtrar

<div class="well">Crear <strong>Filtros</strong> del DataFrame con: (visualizar solo 5 primeros)
   
   1.-Selección de los <strong>hombres</strong> que abordaron el titanic.
   
   2.-Selección de las <strong>mujeres</strong> que abordaron el titanic.
    
   3.-Personas con <strong>mas de 30 años</strong> que abordaron el titanic.
    
   4.-Personas que <strong>pertenecen a la clase 1 y 2</strong> del titanic.
    
   5.-Personas que <strong>registraron su edad.</strong>
   
    
</div>

In [ ]:
display(titanic.head())
titanic.count()

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
0,1,0,3,"Braund, Mr. Owen Harris",Masculino,22.0,0,A/5 21171,7.25,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",Femenino,26.0,0,STON/O2. 3101282,7.93,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",Masculino,35.0,0,373450,8.05,NaN,S

Id_Pasajero    891
Survived       891
Clase          891
Nombre         891
Sexo           891
Edad           714
Familiares     891
Tiquete        891
Tarifa         891
Cabina         204
Embarcado      889
dtype: int64

In [ ]:
#Seleccion de los hombres que abordaron el titanic
titanic_hombres=titanic.copy()
Seleccion_hombres=titanic_hombres[(titanic_hombres['Sexo']== 'Masculino')]
display(Seleccion_hombres.head(6))
Seleccion_hombres.count()

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
0,1,0,3,"Braund, Mr. Owen Harris",Masculino,22.0,0,A/5 21171,7.25,NaN,S
4,5,0,3,"Allen, Mr. William Henry",Masculino,35.0,0,373450,8.05,NaN,S
5,6,0,3,"Moran, Mr. James",Masculino,NaN,0,330877,8.46,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",Masculino,54.0,0,17463,51.86,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",Masculino,2.0,1,349909,21.08,NaN,S
12,13,0,3,"Saundercock, Mr. William Henry",Masculino,20.0,0,A/5. 2151,8.05,NaN,S

Id_Pasajero    577
Survived       577
Clase          577
Nombre         577
Sexo           577
Edad           453
Familiares     577
Tiquete        577
Tarifa         577
Cabina         107
Embarcado      577
dtype: int64

In [ ]:
#Selección de las mujeres que abordaron el titanic.
titanic_mujeres=titanic.copy()
Seleccion_mujeres=titanic_mujeres[(titanic_mujeres['Sexo']== 'Femenino')]
display(Seleccion_mujeres.head(6))
Seleccion_mujeres.count()

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",Femenino,26.0,0,STON/O2. 3101282,7.93,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",Femenino,27.0,2,347742,11.13,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",Femenino,14.0,0,237736,30.07,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",Femenino,4.0,1,PP 9549,16.70,G6,S

Id_Pasajero    314
Survived       314
Clase          314
Nombre         314
Sexo           314
Edad           261
Familiares     314
Tiquete        314
Tarifa         314
Cabina          97
Embarcado      312
dtype: int64

In [ ]:
#Personas con mas de 30 años que abordaron el titanic.
titanic_30=titanic.copy()
Seleccion_30=titanic_30[(titanic_30['Edad'] > 30)]
display(Seleccion_30.head(6))
Seleccion_30.count()

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",Masculino,35.0,0,373450,8.05,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",Masculino,54.0,0,17463,51.86,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",Femenino,58.0,0,113783,26.55,C103,S
13,14,0,3,"Andersson, Mr. Anders Johan",Masculino,39.0,5,347082,31.28,NaN,S

Id_Pasajero    305
Survived       305
Clase          305
Nombre         305
Sexo           305
Edad           305
Familiares     305
Tiquete        305
Tarifa         305
Cabina         116
Embarcado      303
dtype: int64

In [ ]:
#Personas que pertenecen a la clase 1 y 2 del titanic.
titanic_clase=titanic.copy()
Seleccion_clase=titanic_clase[(titanic_clase['Clase'] != 3 )]
display(Seleccion_clase.head(6))
Seleccion_clase.count()

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",Masculino,54.0,0,17463,51.86,E46,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",Femenino,14.0,0,237736,30.07,NaN,C
11,12,1,1,"Bonnell, Miss. Elizabeth",Femenino,58.0,0,113783,26.55,C103,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",Femenino,55.0,0,248706,16.00,NaN,S

Id_Pasajero    400
Survived       400
Clase          400
Nombre         400
Sexo           400
Edad           359
Familiares     400
Tiquete        400
Tarifa         400
Cabina         192
Embarcado      398
dtype: int64

In [ ]:
#Personas que registraron su edad.
titanic_clase=titanic.copy()
Seleccion_clase=titanic_clase[(titanic_clase['Edad'] < 100 )]
display(Seleccion_clase.head(6))
Seleccion_clase.count()
Cantidad=len(Seleccion_clase)
print('Solo registraron su edad: ',Cantidad)

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
0,1,0,3,"Braund, Mr. Owen Harris",Masculino,22.0,0,A/5 21171,7.25,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",Femenino,26.0,0,STON/O2. 3101282,7.93,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",Masculino,35.0,0,373450,8.05,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",Masculino,54.0,0,17463,51.86,E46,S

Solo registraron su edad:  714

### Ejercicio 4 - Investigar Como?  Seleccionar Filas y Columnas

<div class="well">Crear <strong>Selección</strong> del DataFrame con:
   
   1.-Selección de los <strong>nombres</strong> de pasajeros <strong>mayores de 30 años.</strong>
   
   2.-Selección de los <strong>nombres</strong> de las <strong>mujeres</strong> que tienen familiares que abordaron el titanic.
    
   3.-Selección de las <strong>filas 0 a 10 y las columnas 2 a 6.</strong>
    
   
</div>

In [4]:
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
titanic = pd.read_excel('/content/drive/MyDrive/titanic.xlsx')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
#Selección de los nombres de pasajeros mayores de 30 años.
titanic_30=titanic.copy()
Seleccion_30=titanic_30[(titanic_30['Edad'] > 30)]
display(Seleccion_30.loc[: ,['Nombre','Edad']].head())
Seleccion_30.count()

                                               Nombre  Edad
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                            Allen, Mr. William Henry  35.0
6                             McCarthy, Mr. Timothy J  54.0
11                           Bonnell, Miss. Elizabeth  58.0

Id_Pasajero    305
Survived       305
Clase          305
Nombre         305
Sexo           305
Edad           305
Familiares     305
Tiquete        305
Tarifa         305
Cabina         116
Embarcado      303
dtype: int64

In [6]:
#Selección de los nombres de las mujeres que tienen familiares que abordaron el titanic.
titanic_M_F=titanic.copy()
Seleccion_M_F=titanic_M_F[((titanic_M_F['Familiares'] != 0) & (titanic_M_F['Sexo'] =='Femenino'))]
display(Seleccion_M_F.loc[: ,['Nombre','Familiares','Sexo']].head())
Seleccion_M_F.count()

                                               Nombre  Familiares      Sexo
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)           2  Femenino
10                    Sandstrom, Miss. Marguerite Rut           1  Femenino
24                      Palsson, Miss. Torborg Danira           1  Femenino
25  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...           5  Femenino
43           Laroche, Miss. Simonne Marie Anne Andree           2  Femenino

Id_Pasajero    120
Survived       120
Clase          120
Nombre         120
Sexo           120
Edad           108
Familiares     120
Tiquete        120
Tarifa         120
Cabina          36
Embarcado      120
dtype: int64

In [8]:
#Selección de las filas 0 a 10 y las columnas 2 a 6.
display(titanic.head())
print('\n')

titanic.loc[:, ['Clase','Familiares']].head(11)

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
0,1,0,3,"Braund, Mr. Owen Harris",Masculino,22.0,0,A/5 21171,7.25,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",Femenino,26.0,0,STON/O2. 3101282,7.93,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",Masculino,35.0,0,373450,8.05,NaN,S

    Clase  Familiares
0       3           0
1       1           0
2       3           0
3       1           0
4       3           0
5       3           0
6       1           0
7       3           1
8       3           2
9       2           0
10      3           1

### Ejercicio 5 - Investigar Como?

<div class="well">Hallar los <strong>Valores</strong> del DataFrame:
   
   1.-<strong>Valor promedio</strong> de la edad de los pasajeros.
   
   2.-Pasajeros <strong>mujeres</strong> con <strong>mayor edad</strong> que abordaron el titanic.
    
   3.-Pasajeros <strong>mujeres</strong> con <strong>menor edad</strong> que abordaron el titanic.
    
   4.-Número <strong>total de pasajeros</strong> registrados en el titanic
    
   
</div>

In [9]:
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
titanic = pd.read_excel('/content/drive/MyDrive/titanic.xlsx')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [19]:
#Valor promedio de la edad de los pasajeros.
display(titanic.head())
edad_promedio = titanic.Edad.mean()
print('\nLa edad promedio es: ',edad_promedio)

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
0,1,0,3,"Braund, Mr. Owen Harris",Masculino,22.0,0,A/5 21171,7.25,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",Femenino,26.0,0,STON/O2. 3101282,7.93,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",Masculino,35.0,0,373450,8.05,NaN,S

La edad promedio es:  29.69911764705882

In [39]:
#Pasajeros mujeres con mayor edad que abordaron el titanic.(mayor a 60 años)
titanic_M_50=titanic.copy()
Seleccion_M_50=titanic_M_50[((titanic_M_50.Sexo == 'Femenino') & (titanic_M_50.Edad > 60))]
display(Seleccion_M_50.loc[: ,['Edad','Sexo']].head())
Seleccion_M_50.count()

     Edad      Sexo
275  63.0  Femenino
483  63.0  Femenino
829  62.0  Femenino

Id_Pasajero    3
Survived       3
Clase          3
Nombre         3
Sexo           3
Edad           3
Familiares     3
Tiquete        3
Tarifa         3
Cabina         2
Embarcado      2
dtype: int64

In [43]:
#Pasajeros mujeres con menor edad que abordaron el titanic.(maenor de 19)
titanic_M_50=titanic.copy()
Seleccion_M_50=titanic_M_50[((titanic_M_50.Sexo == 'Femenino') & (titanic_M_50.Edad < 19))]
display(Seleccion_M_50.loc[: ,['Edad','Sexo']].head())
Seleccion_M_50.count()

    Edad      Sexo
9   14.0  Femenino
10   4.0  Femenino
14  14.0  Femenino
22  15.0  Femenino
24   8.0  Femenino

Id_Pasajero    68
Survived       68
Clase          68
Nombre         68
Sexo           68
Edad           68
Familiares     68
Tiquete        68
Tarifa         68
Cabina         14
Embarcado      68
dtype: int64

In [48]:
#Número total de pasajeros registrados en el titanic a partir de la cantidad de los nombres.
display(titanic.head())
registrados = len(titanic.loc[:, 'Nombre'])

print("\nNúmero total de pasajeros registrados en el titanic: ",registrados)

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
0,1,0,3,"Braund, Mr. Owen Harris",Masculino,22.0,0,A/5 21171,7.25,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",Femenino,26.0,0,STON/O2. 3101282,7.93,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",Masculino,35.0,0,373450,8.05,NaN,S

Número total de pasajeros registrados en el titanic:  891

![linea 2](https://user-images.githubusercontent.com/19308295/115926262-2fb62980-a448-11eb-8189-c2f10e499944.png)

## <font color=#33A5FF>****BIBLIOGRAFÍA****<tfont>

[1] Guía de pandas oficial https://pandas.pydata.org/docs/user_guide/index.html

[2] Python Pandas Tutorial: A Complete Introduction for Beginners https://bit.ly/2AQMQld

[3] Guía para pandas https://pybonacci.org/2014/05/30/pandas-i/

[4] Dataset variados https://www.kaggle.com/datasets

![linea 1](https://user-images.githubusercontent.com/19308295/115926252-2b8a0c00-a448-11eb-9d9c-b43beaf0ff68.png)